pre-install: Fix service name for cri-o runtime
confidential-containers/operator pull request #424
Opened 2024-08-21 14:28 UTC by ldoktor

the cri-o runtime uses "crio.service" service name (tested on OCP 4.14)

Related to: #418

2024-08-21 14:43 UTC, bpradipt approved these changes
/lgtm

2024-08-21 14:49 UTC, beraldoleal approved these changes
My only concern was that in some systems, cri-o service would be called 'cri-o' instead of 'crio'. But I just tested with ubuntu2204, and both will work, so this LGTM, thanks @ldoktor

2024-08-22 16:13 UTC, GabyCT approved these changes

2024-09-02 08:05 UTC, fidencio commented on install/pre-install-payload/scripts/reqs-deploy.sh
> +	host_systemctl restart "${service_name}"
I'd rather solve this here: https://github.com/confidential-containers/operator/pull/424/files#diff-1d64c80e2d9aea0884eef362ad623406c0edb4de1295dd31579a9270bc428c3eR44

This is what we do on the Kata Containers side: https://github.com/kata-containers/kata-containers/blob/ef5a5ea26e893b1f7fa20bd82eca402b11f08b21/tools/packaging/kata-deploy/scripts/kata-deploy.sh#L609-L610

2024-09-02 08:06 UTC, fidencio requested changes
Requesting changes, as I'd rather have this more aligned with what we do in Kata Containers.

2024-09-02 08:51 UTC, ldoktor commented
@fidencio makes sense to me (although personally I'd move it even directly to `get_container_runtime`). I tried addressing all the places (except one that uses the `local container_runtime` and which should contain the `cri-o`).

2024-09-04 17:29 UTC, fidencio approved these changes
lgtm, thanks @ldoktor!

2024-09-04 21:56 UTC, merged